### ISSUE TITLE
Suggestion : Auto send prompts with Custom URL

### ISSUE THREAD

**Issue by keen0309** [shigeyukey/Anki-Terminator-#17]
Custom URL, automatic suggestions not working. When will it be improved? Can you tell me what to modify? I urgently need it.

**Comment by shigeyukey** [comment]
Thanks for reporting the issue.
The custom URL only display the page for now, it doesn't support prompts.
To auto send a prompt I need to look up the code on the web page and add it, so only ChatGPT and Genimi can auto send. I plan to add Google and others later.

**Comment by keen0309** [comment]
> 感谢您报告此问题。自定义 URL 目前仅显示页面，尚不支持提示功能。为了自动发送提示，我需要查找网页上的代码并添加它，因此目前只有 ChatGPT 和 Genimi 能够自动发送。我计划稍后添加 Google 和其他平台。




I hope to create a tutorial because everyone uses different AI websites. I am willing to pay to customize the URL and add automatic prompts.

**Comment by shigeyukey** [comment]
Prompt input and sending is advanced because it is different for each web page, so I think it is a bit difficult even with using AI because need to read the code. 

If you have any AI or other URLs you would like to use in your custom URLs, please send them all to me, I'll try to see if I can add them as options when I do development.

**Comment by shigeyukey** [comment]
Close as complete because the URL of the AI is unknown.
If you have a request, please reopen it, thank you.
