### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by skyfox6688** [shigeyukey/Anki-Terminator-#20]
![image](https://github.com/user-attachments/assets/7ee32fbb-5e44-4cbf-b519-ad0048bfabd0)
After opening Anki, the plugin will be on the left.
![image](https://github.com/user-attachments/assets/d0512945-9e22-4400-99b0-4b887208bbdd)
This plugin appears broken on AnkiWeb.

**Comment by shigeyukey** [comment]
Hello, thanks for reporting the problem.

This add-on can no longer be updated due to a bug, so I changed it to the new add-on page.
* new add-on code : 1468920185
* new addon page : [🤖Anki Terminator V2](https://ankiweb.net/shared/info/1468920185)

I added a workaround to V2, is the problem still occurring?

**Comment by shigeyukey** [comment]
According to the rating comments on the add-on page, this problem seems to have been resolved in the update. If the problem reoccurs please contact me again.
